---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-pv
spec:
  capacity: 
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/maven

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: maven-repo
  namespace: jenkins
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi