---
apiVersion: v1
kind: Namespace
metadata:
   name: app-two
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplenodeservice
  namespace: app-two
  labels:
    app: simplenodeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplenodeservice
  template:
    metadata:
      labels:
        app: simplenodeservice
        version: v2
    spec:
      containers:
      - name: simplenodeservice
        image: dynatraceace/simplenodeservice:2.0.0
        env:
        - name: DT_TAGS
          value: "event=Perform2021 owner=aceservices@dynatrace.com build=2"
        - name: DT_CUSTOM_PROP
          value: "event=Perform2021 owner=aceservices@dynatrace.com build=2 endpoint=simplenode.app-two.INGRESS_PLACEHOLDER"
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 15
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: simplenodeservice
  namespace: app-two
  labels:
    app: simplenodeservice
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: simplenodeservice
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: simplenodeservice
  name: simplenodeservice
  namespace: app-two
spec:
  rules:
  - host: simplenode.app-two.INGRESS_PLACEHOLDER
    http:
      paths:
      - backend:
          serviceName: simplenodeservice
          servicePort: 80
        path: /
        pathType: ImplementationSpecific